---
- name: Start mongo container
  docker_container:
    name: votedb
    image: library/mongo
    state: started
    hostname: votedb

- name: Start vote-app container
  docker_container:
    name: voteapp
    image: welencm/vote-app
    state: started
    hostname: voteapp
    ports:
      - '8080:8080'
    links:
     - votedb
